# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20160430_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unconfirmed', models.IntegerField(default=0)),
                ('confirmed', models.IntegerField(default=0)),
                ('inProgress', models.IntegerField(default=0)),
                ('waitingForReview', models.IntegerField(default=0)),
                ('blocker', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('major', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('trivial', models.IntegerField(default=0)),
                ('enhancemnet', models.IntegerField(default=0)),
                ('highest', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('normal', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('lowest', models.IntegerField(default=0)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Projects')),
            ],
        ),
    ]
