# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_bugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='projectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Projects', to_field='name'),
        ),
    ]
