# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_auto_20160518_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugs',
            old_name='enhancemnet',
            new_name='enhancement',
        ),
    ]
