# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_auto_20160518_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.FloatField(default=0)),
                ('projectName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scripts.Projects')),
            ],
        ),
    ]
