# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_commit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributorName', models.CharField(max_length=255)),
                ('contributionCount', models.IntegerField(default=0)),
                ('projectName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scripts.Projects')),
            ],
        ),
    ]
