# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0012_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='projectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Projects'),
        ),
    ]
