# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0014_auto_20160528_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceGraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=1000)),
                ('toolUsed', models.CharField(max_length=1000)),
                ('componentName', models.CharField(max_length=1000)),
                ('jenkinsUrl', models.CharField(max_length=1000)),
                ('plotId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='performancegraphs',
            name='mainUrl',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scripts.Urls'),
        ),
        migrations.AlterUniqueTogether(
            name='performancegraphs',
            unique_together=set([('jobName', 'plotId')]),
        ),
    ]
