# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0015_auto_20160601_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(max_length=100023, unique=True),
        ),
    ]
