# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0016_auto_20160601_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancegraphs',
            name='plugin',
            field=models.CharField(default='beryllium', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributors',
            name='contributorName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='performancegraphs',
            unique_together=set([('jobName', 'plotId', 'plugin')]),
        ),
    ]
