# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0017_auto_20160624_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancegraphs',
            name='jenkinsJobName',
            field=models.CharField(default='fuck', max_length=1000),
            preserve_default=False,
        ),
    ]
