# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0020_remove_performancegraphs_wikiname'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancegraphs',
            name='setNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
