# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0021_performancegraphs_setno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('elapsedTime', models.CharField(max_length=1000)),
                ('critical', models.CharField(max_length=1000)),
                ('startTime', models.CharField(max_length=1000)),
                ('testName', models.CharField(max_length=1000)),
            ],
        ),
    ]
