# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0023_auto_20160730_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robotresults',
            unique_together=set([('jobName', 'testName', 'startTime')]),
        ),
    ]
