# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0024_auto_20160730_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RobotResults',
            new_name='robot_results',
        ),
        migrations.RenameField(
            model_name='robot_results',
            old_name='elapsedTime',
            new_name='elapsed_time',
        ),
        migrations.RenameField(
            model_name='robot_results',
            old_name='jobName',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='robot_results',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='robot_results',
            old_name='testName',
            new_name='test_name',
        ),
        migrations.AlterUniqueTogether(
            name='robot_results',
            unique_together=set([('job_name', 'test_name', 'start_time')]),
        ),
    ]
