# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0024_auto_20160730_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('yaxis', models.CharField(max_length=1000)),
                ('plotGroup', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='perfresults',
            unique_together=set([('jobName', 'title')]),
        ),
    ]
