# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0025_auto_20160823_1715'),
        ('scripts', '0026_robot_results_build_number'),
    ]

    operations = [
    ]
