# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-23 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0027_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfResults',
            new_name='perf_results',
        ),
        migrations.RenameField(
            model_name='perf_results',
            old_name='jobName',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='perf_results',
            old_name='plotGroup',
            new_name='plot_group',
        ),
        migrations.AlterUniqueTogether(
            name='perf_results',
            unique_together=set([('job_name', 'title')]),
        ),
    ]
