# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0029_perf_results_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perf_results',
            old_name='value',
            new_name='avg_value',
        ),
        migrations.AddField(
            model_name='perf_results',
            name='max_value',
            field=models.CharField(default='sdf', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perf_results',
            name='min_value',
            field=models.CharField(default='sdfa', max_length=1000),
            preserve_default=False,
        ),
    ]
