# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0030_auto_20160824_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='perf_results',
            name='build_number',
            field=models.CharField(default='sdfs', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='perf_results',
            unique_together=set([]),
        ),
    ]
